const AddReviewActionsConstants = {
    SHOW_WINDOW:'SHOW_WINDOW',
    REST_REVIEW_FORM_CHANGE:'REST_REVIEW_FORM_CHANGE',
    // REST_REVIEW_RATING_CHANGE:'REST_REVIEW_RATING_CHANGE',
    ADD_REVIEW:'ADD_REVIEW',
    ADD_REVIEW_SUCCESS:'ADD_REVIEW_SUCCESS',
    ADD_REVIEW_FAIL:'ADD_REVIEW_FAIL',
};

export { AddReviewActionsConstants}