const ReviewListConstants = {
    GET_REVIEWS: 'GET_REVIEWS',
    GET_REVIEWS_SUCCESS: 'GET_REVIEWS_SUCCESS',
    GET_REVIEWS_FAIL: 'GET_REVIEWS_FAIL',
    ADD_REVIEW_SUCCESS:'ADD_REVIEW_SUCCESS',
  };
  
  export { ReviewListConstants}
  