const ReviewListConstants = {
    GET_REVIEWS: 'GET_REVIEWS',
    GET_REVIEWS_SUCCESS: 'GET_REVIEWS_SUCCESS',
    GET_REVIEWS_FAIL: 'GET_REVIEWS_FAIL',
    ADD_REVIEW_SUCCESS:'ADD_REVIEW_SUCCESS',

  };

  const SearchBarConstants = {
    GET_REST_NAMES: 'GET_REST_NAMES',
    GET_REST_NAMES_SUCCESS: 'GET_REST_NAMES_SUCCESS',
    GET_REST_NAMES_FAIL: 'GET_REST_NAMES_FAIL',

    GET_QUERY: 'GET_QUERY',
    GET_QUERY_SUCCESS: 'GET_QUERY_SUCCESS',
    GET_QUERY_FAIL: 'GET_QUERY_FAIL'

  };

const ReviewViewConstants = {
    SHOW_PROFILE: 'SHOW_PROFILE',
    GOT_USER: 'GOT_USER',
    GOT_USER_FAIL: 'GOT_USER_FAIL',
    DELETE: 'DELETE',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    DELETE_FAILURE: 'DELETE_FAILURE',
    SET_EDIT_WINDOW: 'SET_EDIT_WINDOW',
    RESET_EDIT_WINDOW: 'RESET_EDIT_WINDOW',
    EDIT_REVIEW: 'EDIT_REVIEW',
    EDIT_FAILURE: 'EDIT_FAILURE'
};

const ProfileViewConstants = {
    CLOSE: 'CLOSE'
};

const EditReviewConstants = {
    EDIT_REVIEW_FORM_CHANGE: 'EDIT_REVIEW_FORM_CHANGE'
};

const AdvancedSearchConstants ={
  SHOW_ADVANCED_SEARCH: 'SHOW_ADVANCED_SEARCH',
  ADVANCED_SEARCH_FORM_CHANGE : 'ADVANCED_SEARCH_FORM_CHANGE'
};

export { ReviewListConstants, SearchBarConstants, ReviewViewConstants, ProfileViewConstants, AdvancedSearchConstants, EditReviewConstants}
  