const LoginRegisterConstants = {
    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    OPEN_WINDOW : 'OPEN_WINDOW',
    FIELD_UPDATE: 'FIELD_UPDATE',
    FILE_CHANGE: 'FILE_CHANGE',
    VALIDATE_USERNAME: 'VALIDATE_USERNAME',
    USERNAME_AVAILABLE: 'USERNAME_AVAILABLE',
};

export { LoginRegisterConstants}
